name: CyberTrad
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.50455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002426'
    - '#992730'
    - '#00e3e0'
    - '#008c8c'
    - '#647072'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
